# Generated by Django 4.0.7 on 2023-06-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='copias',
            new_name='copy',
        ),
        migrations.AlterField(
            model_name='loan',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='devolvido',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
