# Generated by Django 4.0.7 on 2023-07-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_rename_copias_loan_copy_alter_loan_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='devolvido',
            new_name='returned',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='prazo',
            new_name='term',
        ),
    ]
