# Generated by Django 4.0.7 on 2023-07-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_autor_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='autor',
        ),
    ]
