# Generated by Django 4.0.7 on 2023-07-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copy',
            old_name='disponibilidade',
            new_name='available',
        ),
    ]
